baseURL = "https://yimoon.blog/"
title = "Yimoon 的個人部落格"
theme = "PaperMod"
languageCode = "zh-tw"
hasCJKLanguage = true
[pagination]
  pagerSize = 10

enableRobotsTXT = true
timeZone = "Asia/Taipei"
[permalinks]
  posts = "/posts/:slug/"

# enableGitInfo = true

# （可選）若你暫時用 Project Pages 又常忘了在 baseURL 加 /repo/，這兩行能減少 404
# relativeURLs = true
# canonifyURLs = true

[params]
  defaultTheme = "auto"           # 自動深/淺色
  ShowReadingTime = true          # 顯示閱讀時間
  ShowPostNavLinks = true         # 上/下一篇
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowLastMod = true
  ShowWordCount = true
  [params.profileMode]
    enabled = true
    title = "Yimoon's blog"
    subtitle = "紀錄有關音樂和生活的碎片  "
    imageUrl = "/images/119A3096.jpg"
    imageTitle = "我的大頭貼"
    imageWidth = 200
    imageHeight = 200
  [[params.profileMode.buttons]]
    name = "文章列表"
    url = "/posts"

    [[params.profileMode.buttons]]
    name = "關於我"
    url = "/about"
  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/joycelee0326"

  [[params.socialIcons]]
    name = "Rss"
    url = "/index.xml"
  
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:Lyra.music.studio@protonmail.com"

[markup.goldmark.renderer]
  unsafe = true                   # 允許文章內嵌少量 HTML

# 讓首頁同時輸出 RSS/JSON（之後要加搜尋或 RSS 會用到）
[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "now"
    name = "近況"
    url = "/now/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於"
    url = "/about/"
    weight = 3

