baseURL = "https://yimoon.blog/"
title = "Yimoon 的個人部落格"
theme = "PaperMod"
locale = "zh-TW"
hasCJKLanguage = true
copyright = "© 2025-2026 [Yimoon 的部落格](https://yimoon.blog/)"
[pagination]
  pagerSize = 10

enableRobotsTXT = true
timeZone = "Asia/Taipei"
[permalinks]
  posts = "/posts/:slug/"

# enableGitInfo = true

# （可選）若你暫時用 Project Pages 又常忘了在 baseURL 加 /repo/，這兩行能減少 404
# relativeURLs = true
# canonifyURLs = true

[params]
  defaultTheme = "auto"           # 自動深/淺色
  ShowReadingTime = true          # 顯示閱讀時間
  ShowPostNavLinks = true         # 上/下一篇
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowLastMod = true
  ShowWordCount = true
  rssFullContent = true
  since = 2025
  [params.assets]
    favicon = "favicon.png"         # 對應到 static 資料夾內的檔名
    favicon16x16 = "favicon.png"    # 選填，可都指到同一張
    favicon32x32 = "favicon.png"    # 選填
    apple_touch_icon = "favicon.png" # 這是給 iPhone 加入主畫面用的圖示
    
  [params.profileMode]
    enabled = true
    title = "Yimoon's blog"
    subtitle = "紀錄有關音樂和生活的碎片  "
    imageUrl = "/images/perform.jpg"
    imageTitle = "我的大頭貼"
    imageWidth = 200
    imageHeight = 200
  [[params.profileMode.buttons]]
    name = "文章列表"
    url = "/posts"

    [[params.profileMode.buttons]]
    name = "關於我"
    url = "/about"
  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/joycelee0326"

  [[params.socialIcons]]
    name = "Rss"
    url = "/index.xml"
  
  [[params.socialIcons]]
    name = "Email"
    url = "mailto:yimoon.blog@proton.me"

[markup.goldmark.renderer]
  unsafe = true                   # 允許文章內嵌少量 HTML

# 讓首頁同時輸出 RSS/JSON（之後要加搜尋或 RSS 會用到）
[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.rss]
    limit = -1 # 選擇性：-1 代表不限制 RSS 輸出的文章數量，預設是 15 篇

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "now"
    name = "近況"
    url = "/now/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於"
    url = "/about/"
    weight = 3
  
  [[menu.main]]
    identifier = "works"
    name = "作品集"
    url = "/works/"
    weight = 4


